### ISSUE TITLE
gcsfs dependency issue

### ISSUE THREAD

**Issue by cgpu** [cgpu/sbas-nf#6]
![image](https://user-images.githubusercontent.com/38183826/87873752-dd794100-c9bb-11ea-997a-d621526bfd00.png)

```diff
Command error:
  Traceback (most recent call last):
    File "/opt/conda/bin/papermill", line 7, in <module>
      from papermill.cli import papermill
    File "/opt/conda/lib/python3.7/site-packages/papermill/__init__.py", line 4, in <module>
      from .execute import execute_notebook
    File "/opt/conda/lib/python3.7/site-packages/papermill/execute.py", line 8, in <module>
      from .iorw import load_notebook_node, write_ipynb, get_pretty_path, local_file_io_cwd
    File "/opt/conda/lib/python3.7/site-packages/papermill/iorw.py", line 46, in <module>
      from gcsfs import GCSFileSystem
    File "/opt/conda/lib/python3.7/site-packages/gcsfs/__init__.py", line 4, in <module>
      from .dask_link import register as register_dask
    File "/opt/conda/lib/python3.7/site-packages/gcsfs/dask_link.py", line 126, in <module>
      register()
    File "/opt/conda/lib/python3.7/site-packages/gcsfs/dask_link.py", line 121, in register
      dask.bytes.core._filesystems['gcs'] = DaskGCSFileSystem
  AttributeError: module 'dask.bytes.core' has no attribute '_filesystems'
```

fix attempt:

```
conda install gcsfs
```

Relevant issue:

https://github.com/dask/dask/issues/5298

**Comment by cgpu** [comment]
Fix with https://github.com/nteract/papermill/issues/342

`conda install gcsfs>=0.2.1`
